<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AssemblyName>LethalMoonUnlocks</AssemblyName>
        <Product>LethalMoonUnlocks</Product>
        <Description>Permanently unlock moons and more</Description>
        <Version>2.4.4</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>

		<PackageId>com.xmods.$(AssemblyName)</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DebugType>portable</DebugType>
    </PropertyGroup>
	
	<!-- Embed Debug Symbols for Easier Debugging -->
	<PropertyGroup>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>embedded</DebugType>
		<!--
        Trim the project path to prevent players from potentially
        viewing Private Information in stack traces.
        -->
		<PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
	</PropertyGroup>

	<Target Name="CopyAssemblyToRelease" AfterTargets="Build">
		<PropertyGroup>
			<CopyToDir>.\release\BepInEx\plugins\</CopyToDir>
		</PropertyGroup>
		<Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFiles="$(CopyToDir)\$(AssemblyName).dll" />
		<Message Text="Copied assembly to $(CopyToDir)" Importance="High" />
	</Target>

	<ItemGroup>
	  <Compile Remove="LethalConstellationsExtension\**" />
	  <EmbeddedResource Remove="LethalConstellationsExtension\**" />
	  <None Remove="LethalConstellationsExtension\**" />
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2022.3.9" IncludeAssets="compile" />
		<PackageReference Include="Xilophor.LethalNetworkAPI" Version="3.*" PrivateAssets="all" />
		<PackageReference Include="LethalCompany.GameLibs.Steam" Version="67.0.0-ngd.0" Publicize="true" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
		<PackageReference Include="TeamXiaolan.DawnLib" Version="0.8.*" PrivateAssets="all" Publicize="true" />
		<PackageReference Include="TeamXiaolan.DawnLib.DuskMod" Version="0.8.*" PrivateAssets="all" Publicize="true" />
		<!-- <PackageReference Include="IAmBatby.LethalLevelLoader" Version="1.4.*" /> -->
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>
	
    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>D:\Games\SteamLibrary\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp.dll</HintPath> 
        </Reference>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>D:\Games\SteamLibrary\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
        <Reference Include="UnityEngine">
            <HintPath>D:\Games\SteamLibrary\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.dll</HintPath> 
        </Reference>
        <Reference Include="Unity.Netcode.Runtime">
            <HintPath>D:\Games\SteamLibrary\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll</HintPath>
        </Reference>
		<Reference Include="LethalQuantities">
			<HintPath>$(APPDATA)\com.kesomannen.gale\lethal-company\profiles\xCore\BepInEx\plugins\BananaPuncher714-LethalQuantities\LethalQuantities.dll</HintPath>
		</Reference>
		<Reference Include="LethalConstellations">
			<HintPath>$(APPDATA)\com.kesomannen.gale\cache\darmuh-LethalConstellations\0.3.2\BepInEx\plugins\darmuh-LethalConstellations\LethalConstellations.dll</HintPath>
		</Reference>
		<Reference Include="LethalLevelLoader">
			<HintPath>$(APPDATA)\com.kesomannen.gale\cache\IAmBatby-LethalLevelLoader\1.6.8\BepInEx\plugins\IAmBatby-LethalLevelLoader\LethalLevelLoader.dll</HintPath>
		</Reference>
		<Reference Include="darmuhsTerminalStuff">
			<HintPath>$(APPDATA)\com.kesomannen.gale\cache\darmuh-darmuhsTerminalStuff\3.9.0\BepInEx\plugins\darmuh-darmuhsTerminalStuff\darmuhsTerminalStuff.dll</HintPath>
		</Reference>
		<Reference Include="OpenLib">
			<HintPath>$(APPDATA)\com.kesomannen.gale\lethal-company\profiles\Debug\BepInEx\plugins\darmuh-OpenLib\OpenLib.dll</HintPath>
		</Reference>
		<Reference Include="WeatherTweaks">
			<HintPath>$(APPDATA)\com.kesomannen.gale\cache\mrov-BetaWeatherTweaksBeta\0.22.0\BepInEx\plugins\mrov-BetaWeatherTweaksBeta\WeatherTweaks.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>